version: 0.2
phases:
  install:
    commands:
      - echo installing phase ...
      - java --version
      - gradle --version
  pre_build:
    commands:
      - git init
      - git remote add master https://$GITHUB_TOKEN@github.com/thdwoqor/terraform-test.git
      - git fetch
      - git checkout -t master/main
      - git submodule init
      - git submodule update --remote
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - echo build successfully done

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - start.sh
