version: 0.2
phases:
  install:
    commands:
      - echo installing phase ...
      - java --version
      - gradle --version
  pre_build:
    commands:
      - mkdir buildZone && cd buildZone
      - git init
      - git clone https://thdwoqor:$GITHUB_TOKEN@github.com/thdwoqor/terraform-test.git
      - git submodule init
      - git submodule update --remote
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - echo build successfully done

artifacts:
  files:
    - buildZone/build/libs/*.jar
    - appspec.yml
    - start.sh
