version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo installing phase ...
      - java --version
      - gradle --version
  pre_build:
    commands:
      - echo pre build phase
      - git submodule update --init --recursive
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - echo build successfully done

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - start.sh
